# Fecha específica para la reunión. 
# Tiene que seguir este mismo formato
fecha: Apr 6 2022 20:00:00 GMT-0300

# Próximo día de la reunión (ojo, agregar los acentos de Miércoles o Sábado)
# Lunes, Martes, Miércoles, Jueves, Viernes, Sábado, Domingo
dia: Lunes

# Hora del próximo día de la reunión
# Tiene que seguir este mismo formato, con comillas dobles y 24hs
hora: "20:00"

# Duración de la reunión (en minutos)
duracion: 60

# Si está habilitado el countdown
# fecha: solo se guía por la fecha, una vez que haya pasado, se deshabilita mostrando un formulario para subscribirse
# recurrente: prioriza fecha (si la fecha ya pasó usa el próximo dia a la hora indicada) sino va por el próximo día a la hora indicada
# off: deshabilita cualquier opción mostrando un formulario para subscribirse
habilitado: fecha

# URL de la reunión a la que redirigir luego de que se llene el formulario
# Si la reunión es con Jitsi (usando un link con jit.si en la dirección) se habilitan las instrucciones
link: https://us02web.zoom.us/j/89029463345

# NO TOCAR - Exclusión de archivos de la generación de la web estática por Jekyll
exclude: ["CNAME", "package.json", "package-lock.json", "README.md"]
